name: Add issue to board
on:
  issues:
    types: [labeled]
jobs:
  print:
    name: Add issue to board
    runs-on: ubuntu-latest
    steps:
    - name: Validate labels
      env:
        GITHUB_TOKEN: ${{ secrets.ASSIGN_TOKEN }}
        MESSAGE: ${{ github.event.client_payload }}
      run: |
        echo $MESSAGE
        
